name: CI/CD Microservices to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: user-service
            docker_image: marinspira/user-service
            app_name: user-service
            port: 8080
          - name: product-service
            docker_image: marinspira/product-service
            app_name: product-service
            port: 8080
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 3) Setup Java 21
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # 4) Build JAR with Maven
      - name: Build JAR (${{ matrix.service.name }})
        working-directory: ${{ matrix.service.name }}
        run: mvn clean package -DskipTests

      # 5) Login Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      # 6) Build image Docker
      - name: Build Docker image ({{ matrix.service.docker_image }})
        working-directory: ${{ matrix.service.name }}
        run: |
          docker build \
            -t ${{ matrix.service.docker_image }}:latest \
            .

      # 7) Push image Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ matrix.service.docker_image }}:latest

  deploy-to-azure:
    name: Deploy to Azure Container Apps
    runs-on: ubuntu-latest
    needs: build-and-push
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 9) Login Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ env.AZURE_CLIENT_SECRET }}

      # 10) Deploy (update) user-service
      - name: Update Container App: user-service
        run: |
          az containerapp update \
            --name user-service \
            --resource-group microservices-rg \
            --image marinspira/user-service:latest \
            --target-port 8080 \
            --cpu 0.25 \
            --memory 0.5Gi

      # 11) Deploy (update) product-service
      - name: Update Container App: product-service
        run: |
          az containerapp update \
            --name product-service \
            --resource-group microservices-rg \
            --image marinspira/product-service:latest \
            --target-port 8081 \
            --cpu 0.25 \
            --memory 0.5Gi
