name: CI/CD Microservices to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-to-azure:
    name: Deploy to Azure Container Apps
    runs-on: ubuntu-latest
    needs: build-and-push
    strategy:
      matrix:
        include:
          - app_name: user-service
            docker_image: marinspira/user-service
            port: 8080
          - app_name: product-service
            docker_image: marinspira/product-service
            port: 8081
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ env.AZURE_CLIENT_SECRET }}

      - name: Update Container App: ${{ matrix.app_name }}
        run: |
          az containerapp update --name ${{ matrix.app_name }} --resource-group microservices-rg --image ${{ matrix.docker_image }}:latest --cpu 0.25 --memory 0.5Gi
          az containerapp ingress update --name ${{ matrix.app_name }} --resource-group microservices-rg --target-port ${{ matrix.port }}